### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by naxeras** [bitbank2/BB-CP#7]
I have Segmentation fault error running in orange pi zero.

root@orangepizero:~/BB-CP# ./bbcp --spi_bus 0 spi_freq 46000000 --flip --lcd_dc 0 --lcd_led 3 --lcd_rst 1
Segmentation fault
root@orangepizero:~/BB-CP# uname -a
Linux orangepizero 4.14.14-sunxi #1 SMP Thu Jan 25 12:20:57 CET 2018 armv7l GNU/Linux

root@orangepizero:~/BB-CP# cat /boot/armbianEnv.txt
verbosity=1
logo=disabled
console=both
disp_mode=1920x1080p60
overlay_prefix=sun8i-h3
overlays=spi-spidev usbhost2 usbhost3
rootdev=UUID=a2c25aee-d15d-4aa7-8f41-ab6bb511776f
param_spidev_spi_bus=0
param_spidev_max_freq=100000000
rootfstype=ext4
usbstoragequirks=0x2537:0x1066:u,0x2537:0x1068:u

root@orangepizero:~/BB-CP# ls /dev/spi*
/dev/spidev0.0

My wiring.

 

TFT       OPIZERO

-------------------

SCLK (SCK) - 23
MOSI (SDA) - 19
MISO - 21
CS - 24
DC (AO) - 13
RST - 11
VCC - 4
GND - 25
LED - 15

Regards.

**Comment by bitbank2** [comment]
It looks like you're passing the wrong pin numbers to BB-BP for the GPIO pins used by DC/RST/LED. The numbers passed to BB-CP must be the pin numbers. In your case, you should use 13, 11, 15

**Comment by naxeras** [comment]
I tryed with the pin numbers but I still with the same problem:

root@orangepizero:~/BB-CP# ./bbcp --spi_bus 0 spi_freq 46000000 --flip --lcd_dc 13 --lcd_led 15 --lcd_rst 11
Segmentation fault

Regards.

**Comment by bitbank2** [comment]
Were you able to run the SPI_LCD demo program successfully? If not, that would be the first place to diagnose the problem.

**Comment by naxeras** [comment]
Hi again, sorry for the delay.

I dont know what is SPI_LCD demo but fbtft_device its working with this parameters:

root@orangepizero:~# cat /etc/modprobe.d/fbtft.conf
options fbtft_device custom name=fb_ili9341 gpios=reset:1,dc:0,led:3 speed=48000000 fps=25 rotate=90 busnum=1 bgr=1 txbuflen=65536

When fbtft_device is loaded spi disapear:

root@orangepizero:~# dmesg | grep spi
[    8.460617] spi spi1.0: spidev spi1.0 100000kHz 8 bits mode=0x00
[    8.460798] spi spi1.0: Deleting spi1.0
[    8.461626] spi spi1.0: fb_ili9341 spi1.0 48000kHz 8 bits mode=0x00
[   10.522750] graphics fb0: fb_ili9341 frame buffer, 320x240, 150 KiB video memory, 64 KiB buffer memory, fps=25, spi1.0 at 48 MHz

root@orangepizero:~# ls /dev/spi*
ls: cannot access '/dev/spi*': No such file or directory

Regards.

**Comment by bitbank2** [comment]
BB-CP uses my https://github.com/bitbank2/SPI_LCD library to draw on the screen. That repo comes with a simple demo to make sure it's working. Please install that, set the proper parameters and see that it works. If it's not working, then BB-CP won't work.

**Comment by naxeras** [comment]
Hi,

I compiled your SPI_LCD repo (came in your instructions for compile BBCP) but i dont found any SPI_LCD demo executable:

root@livebox:~/SPI_LCD# make
cc -c -Wall -O2 spi_lcd.c
cc -c -Wall -O2 fonts.c
ar -rc libspi_lcd.a spi_lcd.o fonts.o ;\
sudo cp libspi_lcd.a /usr/local/lib ;\
sudo cp spi_lcd.h /usr/local/include

root@livebox:~/SPI_LCD# ls
fonts.c  libspi_lcd.a  main.c    make_sample  spi_lcd.c  spi_lcd.o
fonts.o  LICENSE       Makefile  README.md    spi_lcd.h

**Comment by naxeras** [comment]
Sorry I dont see main.c.

I changed main.c with corrected pins and rename your make_sample to Makefile and make lcd.

And its working!!, colors lines and rectangles

> root@livebox:~/SPI_LCD#
>  make
> cc -c -Wall -O2 main.c
> cc main.o -lspi_lcd -lpthread -lm -o lcd
> root@livebox:~/SPI_LCD# ./lcd
> Full screen updates max out at 23.70 FPS
> 2000 random rectangles in 18223 ms

But bbcp is not working :(

With ./bbcp --spi_bus 1 --spi_freq 36000000 --lcd_dc 13 --lcd_led 15 --lcd_rst 11 screen flash in white and then segmentation fault :(

**Comment by bitbank2** [comment]
At this point, it's probably better to email me to get you through this and then I'll comment on the solution when we're finished

**Comment by dglaude** [comment]
Actually, it took me some time to figure out how to test SPI_LCD.
Then I found make -f make_sample and the exe lcd was there.
Maybe you want both the test and library to be build from the same Makefile?
(and yes, this relate to SPI_LCD, not to BB-CP)

**Comment by Fleckz** [comment]
Hey guys, same problem here!
gdb says:
Program received signal SIGSEGV, Segmentation fault.
FBCapture () at main.c:418
418                                             u32 = *pSrc++;

**Comment by bitbank2** [comment]
Hi @Fleckz 
Some questions:
1) What board are you running it on?
2) What LCD resolution?
3) What display resolution?
4) Did you get the SPI_LCD demo to run on your display?
5) Does it work at all or immediately segfault?
6) Are you running it as sudo?

**Comment by Fleckz** [comment]
Yeah, sorry, I should have been more specific:
1) Orange Pi Zero
2) 320x240
3) Huh, maybe there is the problem, I don't have display, there is no HDMI on this board and TV-OUT is disabled!
4) Yeep, SPI_LCD works, kinda slow but it does work (I see moving lines, then rectangles and color text etc...)
5) I can see the display turn ON backglight so it does something, but... it's like 1sec and segfaults!
6) Yep, using WiringPi so, sudo is a must!

Thanks! :)

**Comment by Fleckz** [comment]
Yep, sorry, works OK, never mind guys! :( I enabled TV-OUT and now BB-CP works! Now I need to find where I change resolution, cause picture does not fit in LCD! :)
EDIT: OK, that was also easy in armbian-config, just edit fb0 and fb1 width and height to 320x240

Still have some problems, but those are not related to the Segfault issue:
Warning: the framebuffer bit depth is 32-bpp, ideally it should be 16-bpp for fastest results
Perf test: worst case framerate = 19 FPS
<25FPS indicates there is something not configured correctly with your SW/HW

**Comment by Fleckz** [comment]
32bpp/16bpp is fixed with fbset -depth 16
Now, any ideas how do I get more speed? Tried swaping wiringpi with generic in SPI_LCD, kinda works a bit better, but still <25FPS

**Comment by bitbank2** [comment]
WiringPi is about the slowest possible option. Generic goes faster, but is still not great. Someone needs to write a PIGPIO-like driver for AllWinner CPUs. You can try upping the SPI frequency, some displays can handle up to 50Mhz on AllWinner. If you saw the SPI_LCD demo running slowly, then it might also be error messages output by the SPI driver slowing things down. Some Linux builds have a strange problem on some AllWinner boards.

**Comment by km1kze** [comment]
Excuse me if I interfere in this discussion, but how do you enable TV-OUT in mainline on OPI ZERO?
